#target: prerequisites 
#	command
####################################################
# Author      : longbin
# Created date: 2020-02-19 15:25:14
####################################################

all:
	gcc domain-server.c -o server
	gcc domain-client.c -o client

clean:
	-rm -v server client
