#target: prerequisites 
#	command
####################################################
# Author      : longbin
# Created date: 2020-02-19 15:25:14
####################################################

all:
	g++ udpserver.cpp -o udpserver
	g++ udpclient.cpp -o udpclient

clean:
	-rm -v udpserver udpclient
